source 'https://rubygems.org'
ruby '2.1.2'
gem 'rails', '4.2.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'gon'
group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'sqlite3'
end
gem 'devise'
gem 'devise-i18n'
gem 'figaro', '>= 1.0.0.rc1'
gem 'high_voltage'
gem 'mysql2'
gem 'pundit'
gem 'slim-rails'
gem 'upmin-admin'
gem 'bourbon'
gem 'neat'
gem 'font-awesome-sass'
gem 'paperclip'
gem 'attr_encrypted'
gem 'bower-rails', '~> 0.9.2'
group :development do
  gem 'capistrano', '~> 3.0.1'
  gem 'capistrano-bundler'
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'capistrano-rails-console'
  gem 'capistrano-rvm', '~> 0.1.1'
  gem 'rails_layout'
  gem 'spring-commands-rspec'
end
group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails'
end
group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'selenium-webdriver'
end
